image: node:latest

stages:
  - code-testing
  - staging-server
  - acceptance-testing

linting:
  stage: code-testing
  script:
    - npm install
    - npm run linter

dependency-checks:
  stage: code-testing
  script:
    - npm install
    - npm run dependency

unit-testing:
  stage: code-testing
  script:
  - npm install
  - npm test

code-coverage:
  stage: code-testing
  script:
    - npm install
    - npm run coverage

coverage-report:
  stage: staging-server
  script:
    - npm install
    - npm run coverage
  artifacts:
    paths:
      - docs
    expire_in: 30 days
  only:
    - master

deploy-staging-server:
  stage: staging-server
  script:
  - apt-get update -qy
  - apt-get install -y ruby ruby-dev rubygems-integration
  - gem install dpl
  - dpl --provider=heroku --app=choudh70-e-learning-tool --api-key=5b7672d8-3b76-416c-a4dd-219e960a3e6a
  only:
  - master